export {
  BLOCKED_INSPECTION_MAX_CONFIDENCE,
  BLOCKED_INSPECTION_MAX_SEVERITY,
  MINIMUM_ABSENCE_SOURCES,
  UNCORROBORATED_ABSENCE_MAX_SEVERITY,
} from "@/features/website-assessment/domain/inspection-evidence-policy"
